
//! 123
//! Error
//! EXCEPTION! Test

import lib.libcore


try println(str(123))
with _ => println("Error")


fn test() {
    raise new Exception("error")
}


try test()
with _ => println("Error")


try {
    raise new Exception("Test")
} with
    e => println("EXCEPTION! " + e.msg)


